// Code generated by pigeon; DO NOT EDIT.

// Package ducky — pigeon PEG grammar for Ducky Script V2.
// Regenerate with: go generate ./drivers/usbgadget/ducky/
package ducky

import (
	"bytes"
	"errors"
	"fmt"
	"io"
	"math"
	"os"
	"sort"
	"strconv"
	"strings"
	"sync"
	"unicode"
	"unicode/utf8"
)

// toString converts a pigeon-matched value to a plain string.
// Pigeon returns []byte for literals/classes and []interface{} for repetitions.
func toString(v interface{}) string {
	if v == nil {
		return ""
	}
	switch x := v.(type) {
	case []byte:
		return string(x)
	case string:
		return x
	case []interface{}:
		var b strings.Builder
		for _, c := range x {
			b.WriteString(toString(c))
		}
		return b.String()
	}
	return ""
}

var _ = strconv.Atoi // used in action blocks

var g = &grammar{
	rules: []*rule{
		{
			name: "Script",
			pos:  position{line: 36, col: 1, offset: 704},
			expr: &actionExpr{
				pos: position{line: 36, col: 11, offset: 714},
				run: (*parser).callonScript1,
				expr: &seqExpr{
					pos: position{line: 36, col: 11, offset: 714},
					exprs: []any{
						&labeledExpr{
							pos:   position{line: 36, col: 11, offset: 714},
							label: "instrs",
							expr: &zeroOrMoreExpr{
								pos: position{line: 36, col: 18, offset: 721},
								expr: &ruleRefExpr{
									pos:  position{line: 36, col: 18, offset: 721},
									name: "Line",
								},
							},
						},
						&ruleRefExpr{
							pos:  position{line: 36, col: 24, offset: 727},
							name: "EOF",
						},
					},
				},
			},
		},
		{
			name: "Line",
			pos:  position{line: 47, col: 1, offset: 956},
			expr: &choiceExpr{
				pos: position{line: 47, col: 9, offset: 964},
				alternatives: []any{
					&actionExpr{
						pos: position{line: 47, col: 9, offset: 964},
						run: (*parser).callonLine2,
						expr: &seqExpr{
							pos: position{line: 47, col: 9, offset: 964},
							exprs: []any{
								&ruleRefExpr{
									pos:  position{line: 47, col: 9, offset: 964},
									name: "_",
								},
								&labeledExpr{
									pos:   position{line: 47, col: 11, offset: 966},
									label: "instr",
									expr: &ruleRefExpr{
										pos:  position{line: 47, col: 17, offset: 972},
										name: "Command",
									},
								},
								&ruleRefExpr{
									pos:  position{line: 47, col: 25, offset: 980},
									name: "_",
								},
								&ruleRefExpr{
									pos:  position{line: 47, col: 27, offset: 982},
									name: "EOL",
								},
							},
						},
					},
					&actionExpr{
						pos: position{line: 48, col: 9, offset: 1016},
						run: (*parser).callonLine9,
						expr: &seqExpr{
							pos: position{line: 48, col: 9, offset: 1016},
							exprs: []any{
								&ruleRefExpr{
									pos:  position{line: 48, col: 9, offset: 1016},
									name: "_",
								},
								&ruleRefExpr{
									pos:  position{line: 48, col: 11, offset: 1018},
									name: "EOL",
								},
							},
						},
					},
				},
			},
		},
		{
			name: "Command",
			pos:  position{line: 52, col: 1, offset: 1180},
			expr: &choiceExpr{
				pos: position{line: 52, col: 12, offset: 1191},
				alternatives: []any{
					&ruleRefExpr{
						pos:  position{line: 52, col: 12, offset: 1191},
						name: "Rem",
					},
					&ruleRefExpr{
						pos:  position{line: 53, col: 12, offset: 1206},
						name: "StringLn",
					},
					&ruleRefExpr{
						pos:  position{line: 54, col: 12, offset: 1226},
						name: "StringCmd",
					},
					&ruleRefExpr{
						pos:  position{line: 55, col: 12, offset: 1247},
						name: "DefaultDelay",
					},
					&ruleRefExpr{
						pos:  position{line: 56, col: 12, offset: 1271},
						name: "Delay",
					},
					&ruleRefExpr{
						pos:  position{line: 57, col: 12, offset: 1288},
						name: "KeyLine",
					},
				},
			},
		},
		{
			name: "Rem",
			pos:  position{line: 60, col: 1, offset: 1348},
			expr: &actionExpr{
				pos: position{line: 60, col: 8, offset: 1355},
				run: (*parser).callonRem1,
				expr: &seqExpr{
					pos: position{line: 60, col: 8, offset: 1355},
					exprs: []any{
						&litMatcher{
							pos:        position{line: 60, col: 8, offset: 1355},
							val:        "REM",
							ignoreCase: false,
							want:       "\"REM\"",
						},
						&zeroOrMoreExpr{
							pos: position{line: 60, col: 14, offset: 1361},
							expr: &seqExpr{
								pos: position{line: 60, col: 15, offset: 1362},
								exprs: []any{
									&notExpr{
										pos: position{line: 60, col: 15, offset: 1362},
										expr: &ruleRefExpr{
											pos:  position{line: 60, col: 16, offset: 1363},
											name: "EOL",
										},
									},
									&anyMatcher{
										line: 60, col: 20, offset: 1367,
									},
								},
							},
						},
					},
				},
			},
		},
		{
			name: "StringLn",
			pos:  position{line: 63, col: 1, offset: 1437},
			expr: &actionExpr{
				pos: position{line: 63, col: 13, offset: 1449},
				run: (*parser).callonStringLn1,
				expr: &seqExpr{
					pos: position{line: 63, col: 13, offset: 1449},
					exprs: []any{
						&litMatcher{
							pos:        position{line: 63, col: 13, offset: 1449},
							val:        "STRINGLN",
							ignoreCase: false,
							want:       "\"STRINGLN\"",
						},
						&ruleRefExpr{
							pos:  position{line: 63, col: 24, offset: 1460},
							name: "HWS",
						},
						&labeledExpr{
							pos:   position{line: 63, col: 28, offset: 1464},
							label: "text",
							expr: &ruleRefExpr{
								pos:  position{line: 63, col: 33, offset: 1469},
								name: "RestOfLine",
							},
						},
					},
				},
			},
		},
		{
			name: "StringCmd",
			pos:  position{line: 68, col: 1, offset: 1597},
			expr: &actionExpr{
				pos: position{line: 68, col: 14, offset: 1610},
				run: (*parser).callonStringCmd1,
				expr: &seqExpr{
					pos: position{line: 68, col: 14, offset: 1610},
					exprs: []any{
						&litMatcher{
							pos:        position{line: 68, col: 14, offset: 1610},
							val:        "STRING",
							ignoreCase: false,
							want:       "\"STRING\"",
						},
						&ruleRefExpr{
							pos:  position{line: 68, col: 23, offset: 1619},
							name: "HWS",
						},
						&labeledExpr{
							pos:   position{line: 68, col: 27, offset: 1623},
							label: "text",
							expr: &ruleRefExpr{
								pos:  position{line: 68, col: 32, offset: 1628},
								name: "RestOfLine",
							},
						},
					},
				},
			},
		},
		{
			name: "DefaultDelay",
			pos:  position{line: 73, col: 1, offset: 1791},
			expr: &actionExpr{
				pos: position{line: 73, col: 17, offset: 1807},
				run: (*parser).callonDefaultDelay1,
				expr: &seqExpr{
					pos: position{line: 73, col: 17, offset: 1807},
					exprs: []any{
						&choiceExpr{
							pos: position{line: 73, col: 18, offset: 1808},
							alternatives: []any{
								&litMatcher{
									pos:        position{line: 73, col: 18, offset: 1808},
									val:        "DEFAULT_DELAY",
									ignoreCase: false,
									want:       "\"DEFAULT_DELAY\"",
								},
								&litMatcher{
									pos:        position{line: 73, col: 36, offset: 1826},
									val:        "DEFAULTDELAY",
									ignoreCase: false,
									want:       "\"DEFAULTDELAY\"",
								},
							},
						},
						&ruleRefExpr{
							pos:  position{line: 73, col: 52, offset: 1842},
							name: "HWS",
						},
						&labeledExpr{
							pos:   position{line: 73, col: 56, offset: 1846},
							label: "n",
							expr: &ruleRefExpr{
								pos:  position{line: 73, col: 58, offset: 1848},
								name: "Digits",
							},
						},
					},
				},
			},
		},
		{
			name: "Delay",
			pos:  position{line: 79, col: 1, offset: 1984},
			expr: &actionExpr{
				pos: position{line: 79, col: 10, offset: 1993},
				run: (*parser).callonDelay1,
				expr: &seqExpr{
					pos: position{line: 79, col: 10, offset: 1993},
					exprs: []any{
						&litMatcher{
							pos:        position{line: 79, col: 10, offset: 1993},
							val:        "DELAY",
							ignoreCase: false,
							want:       "\"DELAY\"",
						},
						&ruleRefExpr{
							pos:  position{line: 79, col: 18, offset: 2001},
							name: "HWS",
						},
						&labeledExpr{
							pos:   position{line: 79, col: 22, offset: 2005},
							label: "n",
							expr: &ruleRefExpr{
								pos:  position{line: 79, col: 24, offset: 2007},
								name: "Digits",
							},
						},
					},
				},
			},
		},
		{
			name: "KeyLine",
			pos:  position{line: 86, col: 1, offset: 2218},
			expr: &actionExpr{
				pos: position{line: 86, col: 12, offset: 2229},
				run: (*parser).callonKeyLine1,
				expr: &seqExpr{
					pos: position{line: 86, col: 12, offset: 2229},
					exprs: []any{
						&labeledExpr{
							pos:   position{line: 86, col: 12, offset: 2229},
							label: "first",
							expr: &ruleRefExpr{
								pos:  position{line: 86, col: 18, offset: 2235},
								name: "KeyToken",
							},
						},
						&labeledExpr{
							pos:   position{line: 86, col: 27, offset: 2244},
							label: "rest",
							expr: &zeroOrMoreExpr{
								pos: position{line: 86, col: 32, offset: 2249},
								expr: &actionExpr{
									pos: position{line: 86, col: 33, offset: 2250},
									run: (*parser).callonKeyLine7,
									expr: &seqExpr{
										pos: position{line: 86, col: 33, offset: 2250},
										exprs: []any{
											&ruleRefExpr{
												pos:  position{line: 86, col: 33, offset: 2250},
												name: "HWS",
											},
											&labeledExpr{
												pos:   position{line: 86, col: 37, offset: 2254},
												label: "k",
												expr: &ruleRefExpr{
													pos:  position{line: 86, col: 39, offset: 2256},
													name: "KeyToken",
												},
											},
										},
									},
								},
							},
						},
					},
				},
			},
		},
		{
			name: "KeyToken",
			pos:  position{line: 97, col: 1, offset: 2676},
			expr: &choiceExpr{
				pos: position{line: 97, col: 13, offset: 2688},
				alternatives: []any{
					&actionExpr{
						pos: position{line: 97, col: 13, offset: 2688},
						run: (*parser).callonKeyToken2,
						expr: &seqExpr{
							pos: position{line: 97, col: 13, offset: 2688},
							exprs: []any{
								&labeledExpr{
									pos:   position{line: 97, col: 13, offset: 2688},
									label: "name",
									expr: &choiceExpr{
										pos: position{line: 97, col: 20, offset: 2695},
										alternatives: []any{
											&litMatcher{
												pos:        position{line: 97, col: 20, offset: 2695},
												val:        "COMMAND",
												ignoreCase: false,
												want:       "\"COMMAND\"",
											},
											&litMatcher{
												pos:        position{line: 97, col: 32, offset: 2707},
												val:        "CONTROL",
												ignoreCase: false,
												want:       "\"CONTROL\"",
											},
											&litMatcher{
												pos:        position{line: 97, col: 44, offset: 2719},
												val:        "WINDOWS",
												ignoreCase: false,
												want:       "\"WINDOWS\"",
											},
											&litMatcher{
												pos:        position{line: 98, col: 20, offset: 2750},
												val:        "CTRL",
												ignoreCase: false,
												want:       "\"CTRL\"",
											},
											&litMatcher{
												pos:        position{line: 98, col: 29, offset: 2759},
												val:        "ALT",
												ignoreCase: false,
												want:       "\"ALT\"",
											},
											&litMatcher{
												pos:        position{line: 98, col: 37, offset: 2767},
												val:        "SHIFT",
												ignoreCase: false,
												want:       "\"SHIFT\"",
											},
											&litMatcher{
												pos:        position{line: 98, col: 47, offset: 2777},
												val:        "GUI",
												ignoreCase: false,
												want:       "\"GUI\"",
											},
											&litMatcher{
												pos:        position{line: 99, col: 20, offset: 2804},
												val:        "RETURN",
												ignoreCase: false,
												want:       "\"RETURN\"",
											},
											&litMatcher{
												pos:        position{line: 99, col: 31, offset: 2815},
												val:        "ENTER",
												ignoreCase: false,
												want:       "\"ENTER\"",
											},
											&litMatcher{
												pos:        position{line: 100, col: 20, offset: 2844},
												val:        "ESCAPE",
												ignoreCase: false,
												want:       "\"ESCAPE\"",
											},
											&litMatcher{
												pos:        position{line: 100, col: 31, offset: 2855},
												val:        "ESC",
												ignoreCase: false,
												want:       "\"ESC\"",
											},
											&litMatcher{
												pos:        position{line: 101, col: 20, offset: 2882},
												val:        "BACKSPACE",
												ignoreCase: false,
												want:       "\"BACKSPACE\"",
											},
											&litMatcher{
												pos:        position{line: 102, col: 20, offset: 2915},
												val:        "TAB",
												ignoreCase: false,
												want:       "\"TAB\"",
											},
											&litMatcher{
												pos:        position{line: 103, col: 20, offset: 2942},
												val:        "DELETE",
												ignoreCase: false,
												want:       "\"DELETE\"",
											},
											&litMatcher{
												pos:        position{line: 103, col: 31, offset: 2953},
												val:        "DEL",
												ignoreCase: false,
												want:       "\"DEL\"",
											},
											&litMatcher{
												pos:        position{line: 104, col: 20, offset: 2980},
												val:        "INSERT",
												ignoreCase: false,
												want:       "\"INSERT\"",
											},
											&litMatcher{
												pos:        position{line: 104, col: 31, offset: 2991},
												val:        "HOME",
												ignoreCase: false,
												want:       "\"HOME\"",
											},
											&litMatcher{
												pos:        position{line: 104, col: 40, offset: 3000},
												val:        "END",
												ignoreCase: false,
												want:       "\"END\"",
											},
											&litMatcher{
												pos:        position{line: 105, col: 20, offset: 3027},
												val:        "PAGEUP",
												ignoreCase: false,
												want:       "\"PAGEUP\"",
											},
											&litMatcher{
												pos:        position{line: 105, col: 31, offset: 3038},
												val:        "PAGEDOWN",
												ignoreCase: false,
												want:       "\"PAGEDOWN\"",
											},
											&litMatcher{
												pos:        position{line: 106, col: 20, offset: 3070},
												val:        "UPARROW",
												ignoreCase: false,
												want:       "\"UPARROW\"",
											},
											&litMatcher{
												pos:        position{line: 106, col: 32, offset: 3082},
												val:        "DOWNARROW",
												ignoreCase: false,
												want:       "\"DOWNARROW\"",
											},
											&litMatcher{
												pos:        position{line: 106, col: 46, offset: 3096},
												val:        "LEFTARROW",
												ignoreCase: false,
												want:       "\"LEFTARROW\"",
											},
											&litMatcher{
												pos:        position{line: 106, col: 60, offset: 3110},
												val:        "RIGHTARROW",
												ignoreCase: false,
												want:       "\"RIGHTARROW\"",
											},
											&litMatcher{
												pos:        position{line: 107, col: 20, offset: 3144},
												val:        "CAPSLOCK",
												ignoreCase: false,
												want:       "\"CAPSLOCK\"",
											},
											&litMatcher{
												pos:        position{line: 107, col: 33, offset: 3157},
												val:        "NUMLOCK",
												ignoreCase: false,
												want:       "\"NUMLOCK\"",
											},
											&litMatcher{
												pos:        position{line: 107, col: 45, offset: 3169},
												val:        "SCROLLLOCK",
												ignoreCase: false,
												want:       "\"SCROLLLOCK\"",
											},
											&litMatcher{
												pos:        position{line: 108, col: 20, offset: 3203},
												val:        "PRINTSCREEN",
												ignoreCase: false,
												want:       "\"PRINTSCREEN\"",
											},
											&litMatcher{
												pos:        position{line: 108, col: 36, offset: 3219},
												val:        "PAUSE",
												ignoreCase: false,
												want:       "\"PAUSE\"",
											},
											&litMatcher{
												pos:        position{line: 108, col: 46, offset: 3229},
												val:        "BREAK",
												ignoreCase: false,
												want:       "\"BREAK\"",
											},
											&litMatcher{
												pos:        position{line: 109, col: 20, offset: 3258},
												val:        "SPACE",
												ignoreCase: false,
												want:       "\"SPACE\"",
											},
											&litMatcher{
												pos:        position{line: 109, col: 30, offset: 3268},
												val:        "MENU",
												ignoreCase: false,
												want:       "\"MENU\"",
											},
											&litMatcher{
												pos:        position{line: 109, col: 39, offset: 3277},
												val:        "APP",
												ignoreCase: false,
												want:       "\"APP\"",
											},
											&litMatcher{
												pos:        position{line: 110, col: 20, offset: 3304},
												val:        "F12",
												ignoreCase: false,
												want:       "\"F12\"",
											},
											&litMatcher{
												pos:        position{line: 110, col: 28, offset: 3312},
												val:        "F11",
												ignoreCase: false,
												want:       "\"F11\"",
											},
											&litMatcher{
												pos:        position{line: 110, col: 36, offset: 3320},
												val:        "F10",
												ignoreCase: false,
												want:       "\"F10\"",
											},
											&litMatcher{
												pos:        position{line: 111, col: 20, offset: 3347},
												val:        "F9",
												ignoreCase: false,
												want:       "\"F9\"",
											},
											&litMatcher{
												pos:        position{line: 111, col: 27, offset: 3354},
												val:        "F8",
												ignoreCase: false,
												want:       "\"F8\"",
											},
											&litMatcher{
												pos:        position{line: 111, col: 34, offset: 3361},
												val:        "F7",
												ignoreCase: false,
												want:       "\"F7\"",
											},
											&litMatcher{
												pos:        position{line: 111, col: 41, offset: 3368},
												val:        "F6",
												ignoreCase: false,
												want:       "\"F6\"",
											},
											&litMatcher{
												pos:        position{line: 111, col: 48, offset: 3375},
												val:        "F5",
												ignoreCase: false,
												want:       "\"F5\"",
											},
											&litMatcher{
												pos:        position{line: 111, col: 55, offset: 3382},
												val:        "F4",
												ignoreCase: false,
												want:       "\"F4\"",
											},
											&litMatcher{
												pos:        position{line: 111, col: 62, offset: 3389},
												val:        "F3",
												ignoreCase: false,
												want:       "\"F3\"",
											},
											&litMatcher{
												pos:        position{line: 111, col: 69, offset: 3396},
												val:        "F2",
												ignoreCase: false,
												want:       "\"F2\"",
											},
											&litMatcher{
												pos:        position{line: 111, col: 76, offset: 3403},
												val:        "F1",
												ignoreCase: false,
												want:       "\"F1\"",
											},
										},
									},
								},
								&notExpr{
									pos: position{line: 112, col: 20, offset: 3427},
									expr: &ruleRefExpr{
										pos:  position{line: 112, col: 21, offset: 3428},
										name: "KeyChar",
									},
								},
							},
						},
					},
					&actionExpr{
						pos: position{line: 113, col: 14, offset: 3480},
						run: (*parser).callonKeyToken53,
						expr: &labeledExpr{
							pos:   position{line: 113, col: 14, offset: 3480},
							label: "ch",
							expr: &ruleRefExpr{
								pos:  position{line: 113, col: 17, offset: 3483},
								name: "KeyChar",
							},
						},
					},
				},
			},
		},
		{
			name: "RestOfLine",
			pos:  position{line: 116, col: 1, offset: 3597},
			expr: &actionExpr{
				pos: position{line: 116, col: 15, offset: 3611},
				run: (*parser).callonRestOfLine1,
				expr: &labeledExpr{
					pos:   position{line: 116, col: 15, offset: 3611},
					label: "chars",
					expr: &oneOrMoreExpr{
						pos: position{line: 116, col: 21, offset: 3617},
						expr: &seqExpr{
							pos: position{line: 116, col: 22, offset: 3618},
							exprs: []any{
								&notExpr{
									pos: position{line: 116, col: 22, offset: 3618},
									expr: &ruleRefExpr{
										pos:  position{line: 116, col: 23, offset: 3619},
										name: "EOL",
									},
								},
								&anyMatcher{
									line: 116, col: 27, offset: 3623,
								},
							},
						},
					},
				},
			},
		},
		{
			name: "Digits",
			pos:  position{line: 119, col: 1, offset: 3708},
			expr: &actionExpr{
				pos: position{line: 119, col: 11, offset: 3718},
				run: (*parser).callonDigits1,
				expr: &labeledExpr{
					pos:   position{line: 119, col: 11, offset: 3718},
					label: "d",
					expr: &oneOrMoreExpr{
						pos: position{line: 119, col: 13, offset: 3720},
						expr: &charClassMatcher{
							pos:        position{line: 119, col: 13, offset: 3720},
							val:        "[0-9]",
							ranges:     []rune{'0', '9'},
							ignoreCase: false,
							inverted:   false,
						},
					},
				},
			},
		},
		{
			name: "KeyChar",
			pos:  position{line: 122, col: 1, offset: 3839},
			expr: &charClassMatcher{
				pos:        position{line: 122, col: 12, offset: 3850},
				val:        "[^ \\t\\r\\n]",
				chars:      []rune{' ', '\t', '\r', '\n'},
				ignoreCase: false,
				inverted:   true,
			},
		},
		{
			name: "HWS",
			pos:  position{line: 125, col: 1, offset: 3919},
			expr: &oneOrMoreExpr{
				pos: position{line: 125, col: 8, offset: 3926},
				expr: &charClassMatcher{
					pos:        position{line: 125, col: 8, offset: 3926},
					val:        "[ \\t]",
					chars:      []rune{' ', '\t'},
					ignoreCase: false,
					inverted:   false,
				},
			},
		},
		{
			name: "_",
			pos:  position{line: 128, col: 1, offset: 3975},
			expr: &zeroOrMoreExpr{
				pos: position{line: 128, col: 6, offset: 3980},
				expr: &charClassMatcher{
					pos:        position{line: 128, col: 6, offset: 3980},
					val:        "[ \\t]",
					chars:      []rune{' ', '\t'},
					ignoreCase: false,
					inverted:   false,
				},
			},
		},
		{
			name: "EOL",
			pos:  position{line: 133, col: 1, offset: 4191},
			expr: &choiceExpr{
				pos: position{line: 133, col: 8, offset: 4198},
				alternatives: []any{
					&litMatcher{
						pos:        position{line: 133, col: 8, offset: 4198},
						val:        "\r\n",
						ignoreCase: false,
						want:       "\"\\r\\n\"",
					},
					&litMatcher{
						pos:        position{line: 133, col: 17, offset: 4207},
						val:        "\r",
						ignoreCase: false,
						want:       "\"\\r\"",
					},
					&litMatcher{
						pos:        position{line: 133, col: 24, offset: 4214},
						val:        "\n",
						ignoreCase: false,
						want:       "\"\\n\"",
					},
				},
			},
		},
		{
			name: "EOF",
			pos:  position{line: 136, col: 1, offset: 4245},
			expr: &notExpr{
				pos: position{line: 136, col: 8, offset: 4252},
				expr: &anyMatcher{
					line: 136, col: 9, offset: 4253,
				},
			},
		},
	},
}

func (c *current) onScript1(instrs any) (any, error) {
	var result []Instruction
	for _, v := range instrs.([]interface{}) {
		if v != nil {
			result = append(result, v.(Instruction))
		}
	}
	return result, nil
}

func (p *parser) callonScript1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onScript1(stack["instrs"])
}

func (c *current) onLine2(instr any) (any, error) {
	return instr, nil
}

func (p *parser) callonLine2() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onLine2(stack["instr"])
}

func (c *current) onLine9() (any, error) {
	return nil, nil
}

func (p *parser) callonLine9() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onLine9()
}

func (c *current) onRem1() (any, error) {
	return nil, nil
}

func (p *parser) callonRem1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onRem1()
}

func (c *current) onStringLn1(text any) (any, error) {
	return StringInstr{Text: toString(text), WithEnter: true}, nil
}

func (p *parser) callonStringLn1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onStringLn1(stack["text"])
}

func (c *current) onStringCmd1(text any) (any, error) {
	return StringInstr{Text: toString(text), WithEnter: false}, nil
}

func (p *parser) callonStringCmd1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onStringCmd1(stack["text"])
}

func (c *current) onDefaultDelay1(n any) (any, error) {
	ms, _ := strconv.Atoi(toString(n))
	return DefaultDelayInstr{MS: ms}, nil
}

func (p *parser) callonDefaultDelay1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onDefaultDelay1(stack["n"])
}

func (c *current) onDelay1(n any) (any, error) {
	ms, _ := strconv.Atoi(toString(n))
	return DelayInstr{MS: ms}, nil
}

func (p *parser) callonDelay1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onDelay1(stack["n"])
}

func (c *current) onKeyLine7(k any) (any, error) {
	return k, nil
}

func (p *parser) callonKeyLine7() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onKeyLine7(stack["k"])
}

func (c *current) onKeyLine1(first, rest any) (any, error) {
	keys := []string{toString(first)}
	for _, v := range rest.([]interface{}) {
		keys = append(keys, toString(v))
	}
	return KeyInstr{Keys: keys}, nil
}

func (p *parser) callonKeyLine1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onKeyLine1(stack["first"], stack["rest"])
}

func (c *current) onKeyToken2(name any) (any, error) {
	return toString(name), nil
}

func (p *parser) callonKeyToken2() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onKeyToken2(stack["name"])
}

func (c *current) onKeyToken53(ch any) (any, error) {
	return toString(ch), nil
}

func (p *parser) callonKeyToken53() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onKeyToken53(stack["ch"])
}

func (c *current) onRestOfLine1(chars any) (any, error) {
	return toString(chars), nil
}

func (p *parser) callonRestOfLine1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onRestOfLine1(stack["chars"])
}

func (c *current) onDigits1(d any) (any, error) {
	return toString(d), nil
}

func (p *parser) callonDigits1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onDigits1(stack["d"])
}

var (
	// errNoRule is returned when the grammar to parse has no rule.
	errNoRule = errors.New("grammar has no rule")

	// errInvalidEntrypoint is returned when the specified entrypoint rule
	// does not exit.
	errInvalidEntrypoint = errors.New("invalid entrypoint")

	// errInvalidEncoding is returned when the source is not properly
	// utf8-encoded.
	errInvalidEncoding = errors.New("invalid encoding")

	// errMaxExprCnt is used to signal that the maximum number of
	// expressions have been parsed.
	errMaxExprCnt = errors.New("max number of expressions parsed")
)

// Option is a function that can set an option on the parser. It returns
// the previous setting as an Option.
type Option func(*parser) Option

// MaxExpressions creates an Option to stop parsing after the provided
// number of expressions have been parsed, if the value is 0 then the parser will
// parse for as many steps as needed (possibly an infinite number).
//
// The default for maxExprCnt is 0.
func MaxExpressions(maxExprCnt uint64) Option {
	return func(p *parser) Option {
		oldMaxExprCnt := p.maxExprCnt
		p.maxExprCnt = maxExprCnt
		return MaxExpressions(oldMaxExprCnt)
	}
}

// Entrypoint creates an Option to set the rule name to use as entrypoint.
// The rule name must have been specified in the -alternate-entrypoints
// if generating the parser with the -optimize-grammar flag, otherwise
// it may have been optimized out. Passing an empty string sets the
// entrypoint to the first rule in the grammar.
//
// The default is to start parsing at the first rule in the grammar.
func Entrypoint(ruleName string) Option {
	return func(p *parser) Option {
		oldEntrypoint := p.entrypoint
		p.entrypoint = ruleName
		if ruleName == "" {
			p.entrypoint = g.rules[0].name
		}
		return Entrypoint(oldEntrypoint)
	}
}

// Statistics adds a user provided Stats struct to the parser to allow
// the user to process the results after the parsing has finished.
// Also the key for the "no match" counter is set.
//
// Example usage:
//
//	input := "input"
//	stats := Stats{}
//	_, err := Parse("input-file", []byte(input), Statistics(&stats, "no match"))
//	if err != nil {
//	    log.Panicln(err)
//	}
//	b, err := json.MarshalIndent(stats.ChoiceAltCnt, "", "  ")
//	if err != nil {
//	    log.Panicln(err)
//	}
//	fmt.Println(string(b))
func Statistics(stats *Stats, choiceNoMatch string) Option {
	return func(p *parser) Option {
		oldStats := p.Stats
		p.Stats = stats
		oldChoiceNoMatch := p.choiceNoMatch
		p.choiceNoMatch = choiceNoMatch
		if p.Stats.ChoiceAltCnt == nil {
			p.Stats.ChoiceAltCnt = make(map[string]map[string]int)
		}
		return Statistics(oldStats, oldChoiceNoMatch)
	}
}

// Debug creates an Option to set the debug flag to b. When set to true,
// debugging information is printed to stdout while parsing.
//
// The default is false.
func Debug(b bool) Option {
	return func(p *parser) Option {
		old := p.debug
		p.debug = b
		return Debug(old)
	}
}

// Memoize creates an Option to set the memoize flag to b. When set to true,
// the parser will cache all results so each expression is evaluated only
// once. This guarantees linear parsing time even for pathological cases,
// at the expense of more memory and slower times for typical cases.
//
// The default is false.
func Memoize(b bool) Option {
	return func(p *parser) Option {
		old := p.memoize
		p.memoize = b
		return Memoize(old)
	}
}

// AllowInvalidUTF8 creates an Option to allow invalid UTF-8 bytes.
// Every invalid UTF-8 byte is treated as a utf8.RuneError (U+FFFD)
// by character class matchers and is matched by the any matcher.
// The returned matched value, c.text and c.offset are NOT affected.
//
// The default is false.
func AllowInvalidUTF8(b bool) Option {
	return func(p *parser) Option {
		old := p.allowInvalidUTF8
		p.allowInvalidUTF8 = b
		return AllowInvalidUTF8(old)
	}
}

// Recover creates an Option to set the recover flag to b. When set to
// true, this causes the parser to recover from panics and convert it
// to an error. Setting it to false can be useful while debugging to
// access the full stack trace.
//
// The default is true.
func Recover(b bool) Option {
	return func(p *parser) Option {
		old := p.recover
		p.recover = b
		return Recover(old)
	}
}

// GlobalStore creates an Option to set a key to a certain value in
// the globalStore.
func GlobalStore(key string, value any) Option {
	return func(p *parser) Option {
		old := p.cur.globalStore[key]
		p.cur.globalStore[key] = value
		return GlobalStore(key, old)
	}
}

// InitState creates an Option to set a key to a certain value in
// the global "state" store.
func InitState(key string, value any) Option {
	return func(p *parser) Option {
		old := p.cur.state[key]
		p.cur.state[key] = value
		return InitState(key, old)
	}
}

// ParseFile parses the file identified by filename.
func ParseFile(filename string, opts ...Option) (i any, err error) {
	f, err := os.Open(filename)
	if err != nil {
		return nil, err
	}
	defer func() {
		if closeErr := f.Close(); closeErr != nil {
			err = closeErr
		}
	}()
	return ParseReader(filename, f, opts...)
}

// ParseReader parses the data from r using filename as information in the
// error messages.
func ParseReader(filename string, r io.Reader, opts ...Option) (any, error) {
	b, err := io.ReadAll(r)
	if err != nil {
		return nil, err
	}

	return Parse(filename, b, opts...)
}

// Parse parses the data from b using filename as information in the
// error messages.
func Parse(filename string, b []byte, opts ...Option) (any, error) {
	return newParser(filename, b, opts...).parse(g)
}

// position records a position in the text.
type position struct {
	line, col, offset int
}

func (p position) String() string {
	return strconv.Itoa(p.line) + ":" + strconv.Itoa(p.col) + " [" + strconv.Itoa(p.offset) + "]"
}

// savepoint stores all state required to go back to this point in the
// parser.
type savepoint struct {
	position
	rn rune
	w  int
}

type current struct {
	pos  position // start position of the match
	text []byte   // raw text of the match

	// state is a store for arbitrary key,value pairs that the user wants to be
	// tied to the backtracking of the parser.
	// This is always rolled back if a parsing rule fails.
	state storeDict

	// globalStore is a general store for the user to store arbitrary key-value
	// pairs that they need to manage and that they do not want tied to the
	// backtracking of the parser. This is only modified by the user and never
	// rolled back by the parser. It is always up to the user to keep this in a
	// consistent state.
	globalStore storeDict
}

type storeDict map[string]any

// the AST types...

type grammar struct {
	pos   position
	rules []*rule
}

type rule struct {
	pos         position
	name        string
	displayName string
	expr        any
}

type choiceExpr struct {
	pos          position
	alternatives []any
}

type actionExpr struct {
	pos  position
	expr any
	run  func(*parser) (any, error)
}

type recoveryExpr struct {
	pos          position
	expr         any
	recoverExpr  any
	failureLabel []string
}

type seqExpr struct {
	pos   position
	exprs []any
}

type throwExpr struct {
	pos   position
	label string
}

type labeledExpr struct {
	pos   position
	label string
	expr  any
}

type expr struct {
	pos  position
	expr any
}

type (
	andExpr        expr
	notExpr        expr
	zeroOrOneExpr  expr
	zeroOrMoreExpr expr
	oneOrMoreExpr  expr
)

type ruleRefExpr struct {
	pos  position
	name string
}

type stateCodeExpr struct {
	pos position
	run func(*parser) error
}

type andCodeExpr struct {
	pos position
	run func(*parser) (bool, error)
}

type notCodeExpr struct {
	pos position
	run func(*parser) (bool, error)
}

type litMatcher struct {
	pos        position
	val        string
	ignoreCase bool
	want       string
}

type charClassMatcher struct {
	pos             position
	val             string
	basicLatinChars [128]bool
	chars           []rune
	ranges          []rune
	classes         []*unicode.RangeTable
	ignoreCase      bool
	inverted        bool
}

type anyMatcher position

// errList cumulates the errors found by the parser.
type errList []error

func (e *errList) add(err error) {
	*e = append(*e, err)
}

func (e errList) err() error {
	if len(e) == 0 {
		return nil
	}
	e.dedupe()
	return e
}

func (e *errList) dedupe() {
	var cleaned []error
	set := make(map[string]bool)
	for _, err := range *e {
		if msg := err.Error(); !set[msg] {
			set[msg] = true
			cleaned = append(cleaned, err)
		}
	}
	*e = cleaned
}

func (e errList) Error() string {
	switch len(e) {
	case 0:
		return ""
	case 1:
		return e[0].Error()
	default:
		var buf bytes.Buffer

		for i, err := range e {
			if i > 0 {
				buf.WriteRune('\n')
			}
			buf.WriteString(err.Error())
		}
		return buf.String()
	}
}

// parserError wraps an error with a prefix indicating the rule in which
// the error occurred. The original error is stored in the Inner field.
type parserError struct {
	Inner    error
	pos      position
	prefix   string
	expected []string
}

// Error returns the error message.
func (p *parserError) Error() string {
	return p.prefix + ": " + p.Inner.Error()
}

// newParser creates a parser with the specified input source and options.
func newParser(filename string, b []byte, opts ...Option) *parser {
	stats := Stats{
		ChoiceAltCnt: make(map[string]map[string]int),
	}

	p := &parser{
		filename: filename,
		errs:     new(errList),
		data:     b,
		pt:       savepoint{position: position{line: 1}},
		recover:  true,
		cur: current{
			state:       make(storeDict),
			globalStore: make(storeDict),
		},
		maxFailPos:      position{col: 1, line: 1},
		maxFailExpected: make([]string, 0, 20),
		Stats:           &stats,
		// start rule is rule [0] unless an alternate entrypoint is specified
		entrypoint: g.rules[0].name,
	}
	p.setOptions(opts)

	if p.maxExprCnt == 0 {
		p.maxExprCnt = math.MaxUint64
	}

	return p
}

// setOptions applies the options to the parser.
func (p *parser) setOptions(opts []Option) {
	for _, opt := range opts {
		opt(p)
	}
}

type resultTuple struct {
	v   any
	b   bool
	end savepoint
}

const choiceNoMatch = -1

// Stats stores some statistics, gathered during parsing
type Stats struct {
	// ExprCnt counts the number of expressions processed during parsing
	// This value is compared to the maximum number of expressions allowed
	// (set by the MaxExpressions option).
	ExprCnt uint64

	// ChoiceAltCnt is used to count for each ordered choice expression,
	// which alternative is used how may times.
	// These numbers allow to optimize the order of the ordered choice expression
	// to increase the performance of the parser
	//
	// The outer key of ChoiceAltCnt is composed of the name of the rule as well
	// as the line and the column of the ordered choice.
	// The inner key of ChoiceAltCnt is the number (one-based) of the matching alternative.
	// For each alternative the number of matches are counted. If an ordered choice does not
	// match, a special counter is incremented. The name of this counter is set with
	// the parser option Statistics.
	// For an alternative to be included in ChoiceAltCnt, it has to match at least once.
	ChoiceAltCnt map[string]map[string]int
}

type parser struct {
	filename string
	pt       savepoint
	cur      current

	data []byte
	errs *errList

	depth   int
	recover bool
	debug   bool

	memoize bool
	// memoization table for the packrat algorithm:
	// map[offset in source] map[expression or rule] {value, match}
	memo map[int]map[any]resultTuple

	// rules table, maps the rule identifier to the rule node
	rules map[string]*rule
	// variables stack, map of label to value
	vstack []map[string]any
	// rule stack, allows identification of the current rule in errors
	rstack []*rule

	// parse fail
	maxFailPos            position
	maxFailExpected       []string
	maxFailInvertExpected bool

	// max number of expressions to be parsed
	maxExprCnt uint64
	// entrypoint for the parser
	entrypoint string

	allowInvalidUTF8 bool

	*Stats

	choiceNoMatch string
	// recovery expression stack, keeps track of the currently available recovery expression, these are traversed in reverse
	recoveryStack []map[string]any
}

// push a variable set on the vstack.
func (p *parser) pushV() {
	if cap(p.vstack) == len(p.vstack) {
		// create new empty slot in the stack
		p.vstack = append(p.vstack, nil)
	} else {
		// slice to 1 more
		p.vstack = p.vstack[:len(p.vstack)+1]
	}

	// get the last args set
	m := p.vstack[len(p.vstack)-1]
	if m != nil && len(m) == 0 {
		// empty map, all good
		return
	}

	m = make(map[string]any)
	p.vstack[len(p.vstack)-1] = m
}

// pop a variable set from the vstack.
func (p *parser) popV() {
	// if the map is not empty, clear it
	m := p.vstack[len(p.vstack)-1]
	if len(m) > 0 {
		// GC that map
		p.vstack[len(p.vstack)-1] = nil
	}
	p.vstack = p.vstack[:len(p.vstack)-1]
}

// push a recovery expression with its labels to the recoveryStack
func (p *parser) pushRecovery(labels []string, expr any) {
	if cap(p.recoveryStack) == len(p.recoveryStack) {
		// create new empty slot in the stack
		p.recoveryStack = append(p.recoveryStack, nil)
	} else {
		// slice to 1 more
		p.recoveryStack = p.recoveryStack[:len(p.recoveryStack)+1]
	}

	m := make(map[string]any, len(labels))
	for _, fl := range labels {
		m[fl] = expr
	}
	p.recoveryStack[len(p.recoveryStack)-1] = m
}

// pop a recovery expression from the recoveryStack
func (p *parser) popRecovery() {
	// GC that map
	p.recoveryStack[len(p.recoveryStack)-1] = nil

	p.recoveryStack = p.recoveryStack[:len(p.recoveryStack)-1]
}

func (p *parser) print(prefix, s string) string {
	if !p.debug {
		return s
	}

	fmt.Printf("%s %d:%d:%d: %s [%#U]\n",
		prefix, p.pt.line, p.pt.col, p.pt.offset, s, p.pt.rn)
	return s
}

func (p *parser) printIndent(mark string, s string) string {
	return p.print(strings.Repeat(" ", p.depth)+mark, s)
}

func (p *parser) in(s string) string {
	res := p.printIndent(">", s)
	p.depth++
	return res
}

func (p *parser) out(s string) string {
	p.depth--
	return p.printIndent("<", s)
}

func (p *parser) addErr(err error) {
	p.addErrAt(err, p.pt.position, []string{})
}

func (p *parser) addErrAt(err error, pos position, expected []string) {
	var buf bytes.Buffer
	if p.filename != "" {
		buf.WriteString(p.filename)
	}
	if buf.Len() > 0 {
		buf.WriteString(":")
	}
	buf.WriteString(fmt.Sprintf("%d:%d (%d)", pos.line, pos.col, pos.offset))
	if len(p.rstack) > 0 {
		if buf.Len() > 0 {
			buf.WriteString(": ")
		}
		rule := p.rstack[len(p.rstack)-1]
		if rule.displayName != "" {
			buf.WriteString("rule " + rule.displayName)
		} else {
			buf.WriteString("rule " + rule.name)
		}
	}
	pe := &parserError{Inner: err, pos: pos, prefix: buf.String(), expected: expected}
	p.errs.add(pe)
}

func (p *parser) failAt(fail bool, pos position, want string) {
	// process fail if parsing fails and not inverted or parsing succeeds and invert is set
	if fail == p.maxFailInvertExpected {
		if pos.offset < p.maxFailPos.offset {
			return
		}

		if pos.offset > p.maxFailPos.offset {
			p.maxFailPos = pos
			p.maxFailExpected = p.maxFailExpected[:0]
		}

		if p.maxFailInvertExpected {
			want = "!" + want
		}
		p.maxFailExpected = append(p.maxFailExpected, want)
	}
}

// read advances the parser to the next rune.
func (p *parser) read() {
	p.pt.offset += p.pt.w
	rn, n := utf8.DecodeRune(p.data[p.pt.offset:])
	p.pt.rn = rn
	p.pt.w = n
	p.pt.col++
	if rn == '\n' {
		p.pt.line++
		p.pt.col = 0
	}

	if rn == utf8.RuneError && n == 1 { // see utf8.DecodeRune
		if !p.allowInvalidUTF8 {
			p.addErr(errInvalidEncoding)
		}
	}
}

// restore parser position to the savepoint pt.
func (p *parser) restore(pt savepoint) {
	if p.debug {
		defer p.out(p.in("restore"))
	}
	if pt.offset == p.pt.offset {
		return
	}
	p.pt = pt
}

// Cloner is implemented by any value that has a Clone method, which returns a
// copy of the value. This is mainly used for types which are not passed by
// value (e.g map, slice, chan) or structs that contain such types.
//
// This is used in conjunction with the global state feature to create proper
// copies of the state to allow the parser to properly restore the state in
// the case of backtracking.
type Cloner interface {
	Clone() any
}

var statePool = &sync.Pool{
	New: func() any { return make(storeDict) },
}

func (sd storeDict) Discard() {
	for k := range sd {
		delete(sd, k)
	}
	statePool.Put(sd)
}

// clone and return parser current state.
func (p *parser) cloneState() storeDict {
	if p.debug {
		defer p.out(p.in("cloneState"))
	}

	state := statePool.Get().(storeDict)
	for k, v := range p.cur.state {
		if c, ok := v.(Cloner); ok {
			state[k] = c.Clone()
		} else {
			state[k] = v
		}
	}
	return state
}

// restore parser current state to the state storeDict.
// every restoreState should applied only one time for every cloned state
func (p *parser) restoreState(state storeDict) {
	if p.debug {
		defer p.out(p.in("restoreState"))
	}
	p.cur.state.Discard()
	p.cur.state = state
}

// get the slice of bytes from the savepoint start to the current position.
func (p *parser) sliceFrom(start savepoint) []byte {
	return p.data[start.position.offset:p.pt.position.offset]
}

func (p *parser) getMemoized(node any) (resultTuple, bool) {
	if len(p.memo) == 0 {
		return resultTuple{}, false
	}
	m := p.memo[p.pt.offset]
	if len(m) == 0 {
		return resultTuple{}, false
	}
	res, ok := m[node]
	return res, ok
}

func (p *parser) setMemoized(pt savepoint, node any, tuple resultTuple) {
	if p.memo == nil {
		p.memo = make(map[int]map[any]resultTuple)
	}
	m := p.memo[pt.offset]
	if m == nil {
		m = make(map[any]resultTuple)
		p.memo[pt.offset] = m
	}
	m[node] = tuple
}

func (p *parser) buildRulesTable(g *grammar) {
	p.rules = make(map[string]*rule, len(g.rules))
	for _, r := range g.rules {
		p.rules[r.name] = r
	}
}

func (p *parser) parse(g *grammar) (val any, err error) {
	if len(g.rules) == 0 {
		p.addErr(errNoRule)
		return nil, p.errs.err()
	}

	// TODO : not super critical but this could be generated
	p.buildRulesTable(g)

	if p.recover {
		// panic can be used in action code to stop parsing immediately
		// and return the panic as an error.
		defer func() {
			if e := recover(); e != nil {
				if p.debug {
					defer p.out(p.in("panic handler"))
				}
				val = nil
				switch e := e.(type) {
				case error:
					p.addErr(e)
				default:
					p.addErr(fmt.Errorf("%v", e))
				}
				err = p.errs.err()
			}
		}()
	}

	startRule, ok := p.rules[p.entrypoint]
	if !ok {
		p.addErr(errInvalidEntrypoint)
		return nil, p.errs.err()
	}

	p.read() // advance to first rune
	val, ok = p.parseRuleWrap(startRule)
	if !ok {
		if len(*p.errs) == 0 {
			// If parsing fails, but no errors have been recorded, the expected values
			// for the farthest parser position are returned as error.
			maxFailExpectedMap := make(map[string]struct{}, len(p.maxFailExpected))
			for _, v := range p.maxFailExpected {
				maxFailExpectedMap[v] = struct{}{}
			}
			expected := make([]string, 0, len(maxFailExpectedMap))
			eof := false
			if _, ok := maxFailExpectedMap["!."]; ok {
				delete(maxFailExpectedMap, "!.")
				eof = true
			}
			for k := range maxFailExpectedMap {
				expected = append(expected, k)
			}
			sort.Strings(expected)
			if eof {
				expected = append(expected, "EOF")
			}
			p.addErrAt(errors.New("no match found, expected: "+listJoin(expected, ", ", "or")), p.maxFailPos, expected)
		}

		return nil, p.errs.err()
	}
	return val, p.errs.err()
}

func listJoin(list []string, sep string, lastSep string) string {
	switch len(list) {
	case 0:
		return ""
	case 1:
		return list[0]
	default:
		return strings.Join(list[:len(list)-1], sep) + " " + lastSep + " " + list[len(list)-1]
	}
}

func (p *parser) parseRuleMemoize(rule *rule) (any, bool) {
	res, ok := p.getMemoized(rule)
	if ok {
		p.restore(res.end)
		return res.v, res.b
	}

	startMark := p.pt
	val, ok := p.parseRule(rule)
	p.setMemoized(startMark, rule, resultTuple{val, ok, p.pt})

	return val, ok
}

func (p *parser) parseRuleWrap(rule *rule) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseRule " + rule.name))
	}
	var (
		val       any
		ok        bool
		startMark = p.pt
	)

	if p.memoize {
		val, ok = p.parseRuleMemoize(rule)
	} else {
		val, ok = p.parseRule(rule)
	}

	if ok && p.debug {
		p.printIndent("MATCH", string(p.sliceFrom(startMark)))
	}
	return val, ok
}

func (p *parser) parseRule(rule *rule) (any, bool) {
	p.rstack = append(p.rstack, rule)
	p.pushV()
	val, ok := p.parseExprWrap(rule.expr)
	p.popV()
	p.rstack = p.rstack[:len(p.rstack)-1]
	return val, ok
}

func (p *parser) parseExprWrap(expr any) (any, bool) {
	var pt savepoint

	if p.memoize {
		res, ok := p.getMemoized(expr)
		if ok {
			p.restore(res.end)
			return res.v, res.b
		}
		pt = p.pt
	}

	val, ok := p.parseExpr(expr)

	if p.memoize {
		p.setMemoized(pt, expr, resultTuple{val, ok, p.pt})
	}
	return val, ok
}

func (p *parser) parseExpr(expr any) (any, bool) {
	p.ExprCnt++
	if p.ExprCnt > p.maxExprCnt {
		panic(errMaxExprCnt)
	}

	var val any
	var ok bool
	switch expr := expr.(type) {
	case *actionExpr:
		val, ok = p.parseActionExpr(expr)
	case *andCodeExpr:
		val, ok = p.parseAndCodeExpr(expr)
	case *andExpr:
		val, ok = p.parseAndExpr(expr)
	case *anyMatcher:
		val, ok = p.parseAnyMatcher(expr)
	case *charClassMatcher:
		val, ok = p.parseCharClassMatcher(expr)
	case *choiceExpr:
		val, ok = p.parseChoiceExpr(expr)
	case *labeledExpr:
		val, ok = p.parseLabeledExpr(expr)
	case *litMatcher:
		val, ok = p.parseLitMatcher(expr)
	case *notCodeExpr:
		val, ok = p.parseNotCodeExpr(expr)
	case *notExpr:
		val, ok = p.parseNotExpr(expr)
	case *oneOrMoreExpr:
		val, ok = p.parseOneOrMoreExpr(expr)
	case *recoveryExpr:
		val, ok = p.parseRecoveryExpr(expr)
	case *ruleRefExpr:
		val, ok = p.parseRuleRefExpr(expr)
	case *seqExpr:
		val, ok = p.parseSeqExpr(expr)
	case *stateCodeExpr:
		val, ok = p.parseStateCodeExpr(expr)
	case *throwExpr:
		val, ok = p.parseThrowExpr(expr)
	case *zeroOrMoreExpr:
		val, ok = p.parseZeroOrMoreExpr(expr)
	case *zeroOrOneExpr:
		val, ok = p.parseZeroOrOneExpr(expr)
	default:
		panic(fmt.Sprintf("unknown expression type %T", expr))
	}
	return val, ok
}

func (p *parser) parseActionExpr(act *actionExpr) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseActionExpr"))
	}

	start := p.pt
	val, ok := p.parseExprWrap(act.expr)
	if ok {
		p.cur.pos = start.position
		p.cur.text = p.sliceFrom(start)
		state := p.cloneState()
		actVal, err := act.run(p)
		if err != nil {
			p.addErrAt(err, start.position, []string{})
		}
		p.restoreState(state)

		val = actVal
	}
	if ok && p.debug {
		p.printIndent("MATCH", string(p.sliceFrom(start)))
	}
	return val, ok
}

func (p *parser) parseAndCodeExpr(and *andCodeExpr) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseAndCodeExpr"))
	}

	state := p.cloneState()

	ok, err := and.run(p)
	if err != nil {
		p.addErr(err)
	}
	p.restoreState(state)

	return nil, ok
}

func (p *parser) parseAndExpr(and *andExpr) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseAndExpr"))
	}

	pt := p.pt
	state := p.cloneState()
	p.pushV()
	_, ok := p.parseExprWrap(and.expr)
	p.popV()
	p.restoreState(state)
	p.restore(pt)

	return nil, ok
}

func (p *parser) parseAnyMatcher(any *anyMatcher) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseAnyMatcher"))
	}

	if p.pt.rn == utf8.RuneError && p.pt.w == 0 {
		// EOF - see utf8.DecodeRune
		p.failAt(false, p.pt.position, ".")
		return nil, false
	}
	start := p.pt
	p.read()
	p.failAt(true, start.position, ".")
	return p.sliceFrom(start), true
}

func (p *parser) parseCharClassMatcher(chr *charClassMatcher) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseCharClassMatcher"))
	}

	cur := p.pt.rn
	start := p.pt

	// can't match EOF
	if cur == utf8.RuneError && p.pt.w == 0 { // see utf8.DecodeRune
		p.failAt(false, start.position, chr.val)
		return nil, false
	}

	if chr.ignoreCase {
		cur = unicode.ToLower(cur)
	}

	// try to match in the list of available chars
	for _, rn := range chr.chars {
		if rn == cur {
			if chr.inverted {
				p.failAt(false, start.position, chr.val)
				return nil, false
			}
			p.read()
			p.failAt(true, start.position, chr.val)
			return p.sliceFrom(start), true
		}
	}

	// try to match in the list of ranges
	for i := 0; i < len(chr.ranges); i += 2 {
		if cur >= chr.ranges[i] && cur <= chr.ranges[i+1] {
			if chr.inverted {
				p.failAt(false, start.position, chr.val)
				return nil, false
			}
			p.read()
			p.failAt(true, start.position, chr.val)
			return p.sliceFrom(start), true
		}
	}

	// try to match in the list of Unicode classes
	for _, cl := range chr.classes {
		if unicode.Is(cl, cur) {
			if chr.inverted {
				p.failAt(false, start.position, chr.val)
				return nil, false
			}
			p.read()
			p.failAt(true, start.position, chr.val)
			return p.sliceFrom(start), true
		}
	}

	if chr.inverted {
		p.read()
		p.failAt(true, start.position, chr.val)
		return p.sliceFrom(start), true
	}
	p.failAt(false, start.position, chr.val)
	return nil, false
}

func (p *parser) incChoiceAltCnt(ch *choiceExpr, altI int) {
	choiceIdent := fmt.Sprintf("%s %d:%d", p.rstack[len(p.rstack)-1].name, ch.pos.line, ch.pos.col)
	m := p.ChoiceAltCnt[choiceIdent]
	if m == nil {
		m = make(map[string]int)
		p.ChoiceAltCnt[choiceIdent] = m
	}
	// We increment altI by 1, so the keys do not start at 0
	alt := strconv.Itoa(altI + 1)
	if altI == choiceNoMatch {
		alt = p.choiceNoMatch
	}
	m[alt]++
}

func (p *parser) parseChoiceExpr(ch *choiceExpr) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseChoiceExpr"))
	}

	for altI, alt := range ch.alternatives {
		// dummy assignment to prevent compile error if optimized
		_ = altI

		state := p.cloneState()

		p.pushV()
		val, ok := p.parseExprWrap(alt)
		p.popV()
		if ok {
			p.incChoiceAltCnt(ch, altI)
			return val, ok
		}
		p.restoreState(state)
	}
	p.incChoiceAltCnt(ch, choiceNoMatch)
	return nil, false
}

func (p *parser) parseLabeledExpr(lab *labeledExpr) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseLabeledExpr"))
	}

	p.pushV()
	val, ok := p.parseExprWrap(lab.expr)
	p.popV()
	if ok && lab.label != "" {
		m := p.vstack[len(p.vstack)-1]
		m[lab.label] = val
	}
	return val, ok
}

func (p *parser) parseLitMatcher(lit *litMatcher) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseLitMatcher"))
	}

	start := p.pt
	for _, want := range lit.val {
		cur := p.pt.rn
		if lit.ignoreCase {
			cur = unicode.ToLower(cur)
		}
		if cur != want {
			p.failAt(false, start.position, lit.want)
			p.restore(start)
			return nil, false
		}
		p.read()
	}
	p.failAt(true, start.position, lit.want)
	return p.sliceFrom(start), true
}

func (p *parser) parseNotCodeExpr(not *notCodeExpr) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseNotCodeExpr"))
	}

	state := p.cloneState()

	ok, err := not.run(p)
	if err != nil {
		p.addErr(err)
	}
	p.restoreState(state)

	return nil, !ok
}

func (p *parser) parseNotExpr(not *notExpr) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseNotExpr"))
	}

	pt := p.pt
	state := p.cloneState()
	p.pushV()
	p.maxFailInvertExpected = !p.maxFailInvertExpected
	_, ok := p.parseExprWrap(not.expr)
	p.maxFailInvertExpected = !p.maxFailInvertExpected
	p.popV()
	p.restoreState(state)
	p.restore(pt)

	return nil, !ok
}

func (p *parser) parseOneOrMoreExpr(expr *oneOrMoreExpr) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseOneOrMoreExpr"))
	}

	var vals []any

	for {
		p.pushV()
		val, ok := p.parseExprWrap(expr.expr)
		p.popV()
		if !ok {
			if len(vals) == 0 {
				// did not match once, no match
				return nil, false
			}
			return vals, true
		}
		vals = append(vals, val)
	}
}

func (p *parser) parseRecoveryExpr(recover *recoveryExpr) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseRecoveryExpr (" + strings.Join(recover.failureLabel, ",") + ")"))
	}

	p.pushRecovery(recover.failureLabel, recover.recoverExpr)
	val, ok := p.parseExprWrap(recover.expr)
	p.popRecovery()

	return val, ok
}

func (p *parser) parseRuleRefExpr(ref *ruleRefExpr) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseRuleRefExpr " + ref.name))
	}

	if ref.name == "" {
		panic(fmt.Sprintf("%s: invalid rule: missing name", ref.pos))
	}

	rule := p.rules[ref.name]
	if rule == nil {
		p.addErr(fmt.Errorf("undefined rule: %s", ref.name))
		return nil, false
	}
	return p.parseRuleWrap(rule)
}

func (p *parser) parseSeqExpr(seq *seqExpr) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseSeqExpr"))
	}

	vals := make([]any, 0, len(seq.exprs))

	pt := p.pt
	state := p.cloneState()
	for _, expr := range seq.exprs {
		val, ok := p.parseExprWrap(expr)
		if !ok {
			p.restoreState(state)
			p.restore(pt)
			return nil, false
		}
		vals = append(vals, val)
	}
	return vals, true
}

func (p *parser) parseStateCodeExpr(state *stateCodeExpr) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseStateCodeExpr"))
	}

	err := state.run(p)
	if err != nil {
		p.addErr(err)
	}
	return nil, true
}

func (p *parser) parseThrowExpr(expr *throwExpr) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseThrowExpr"))
	}

	for i := len(p.recoveryStack) - 1; i >= 0; i-- {
		if recoverExpr, ok := p.recoveryStack[i][expr.label]; ok {
			if val, ok := p.parseExprWrap(recoverExpr); ok {
				return val, ok
			}
		}
	}

	return nil, false
}

func (p *parser) parseZeroOrMoreExpr(expr *zeroOrMoreExpr) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseZeroOrMoreExpr"))
	}

	var vals []any

	for {
		p.pushV()
		val, ok := p.parseExprWrap(expr.expr)
		p.popV()
		if !ok {
			return vals, true
		}
		vals = append(vals, val)
	}
}

func (p *parser) parseZeroOrOneExpr(expr *zeroOrOneExpr) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseZeroOrOneExpr"))
	}

	p.pushV()
	val, _ := p.parseExprWrap(expr.expr)
	p.popV()
	// whether it matched or not, consider it a match
	return val, true
}
